-- Table: plan

-- DROP TABLE plan;

CREATE TABLE plan
(
  id_plan character(10) NOT NULL,
  descripcion text,
  CONSTRAINT plan_pk PRIMARY KEY (id_plan)
)
WITH ( OIDS=FALSE );
ALTER TABLE plan OWNER TO postgres;

INSERT INTO plan VALUES('3M','3 MESES SIN INTERESES');
INSERT INTO plan VALUES('6M','6 MESES SIN INTERESES');
INSERT INTO plan VALUES('9M','9 MESES SIN INTERESES');
INSERT INTO plan VALUES('12M','12 MESES SIN INTERESES');
INSERT INTO plan VALUES('NTC','NORMAL TARJETA DE CREDITO');
